{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-tenant-console.serviceAccountName" . }}
  labels:
    {{- include "kube-tenant-console.labels" . | nindent 4 }}
{{- end }}
