replicaCount: 1

image:
  repository: kube-tenant-console
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  clusterAdmin: true

service:
  type: ClusterIP
  port: 80

env:
  addr: ":8080"
  dataPath: "/data/state.json"
  allowClusterScope: "false"

persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
